### ISSUE TITLE
Every config change causes a rebuild of microvm-bootdisk.img

### ISSUE THREAD

**Issue by oddlama** [astro/microvm.nix#101]
Since your recent change https://github.com/astro/microvm.nix/commit/583785ae6c046288c8451667f3182ffee9662006, any change to a declarative configuration causes an unnecessary rebuild of `microvm-bootdisk.img`. This takes 1-2 minutes for each defined vm, which adds up quickly. The reason is that the derivation changes because this specific line

https://github.com/astro/microvm.nix/blob/3683f43a37568fbc14bdc1c952acb41b0bb09a01/nixos-modules/microvm/root-disk.nix#L126

includes the current kernel parameters into the build script (which of course change for each new generation). Before the change you passed the parameters dynamically in the command for each runner, which doesn't exhibit this problem. I'm not sure whether something in your change specifically requires this to be built into the boot disk, but if possible I'd recommend moving back to dynamic parameters to avoid those rebuilds.

**Comment by astro** [comment]
That boot partition is actually required only for cloud-hypervisor. We could skip that for the other hypervisors which can load an initrd themselves.

But is there any remedy potential for cloud-hypervisor+rust-hypervisor-firmware?

**Comment by oddlama** [comment]
I think you can just use `--cmdline ${lib.escapeShellArg cmdline}` with `cmdline = "${lib.concatStringsSep " " config.microvm.kernelParams} console=ttyS0 reboot=t panic=-1"` instead of adding it to the bootdisk. Or is there something I'm missing?

**Comment by astro** [comment]
I didn't know but cloud-hypervisor [takes into account both sources of cmdline](https://github.com/cloud-hypervisor/rust-hypervisor-firmware/blob/adfaf55b02209349a8e90cd690bd441bf69b64fd/src/loader.rs#L247) indeed!

**Comment by astro** [comment]
With 708f09d5a093af670aa4a7ae4d9d0b0a10f31276 rebuilds are even more fine-grained and optional.
