### ISSUE TITLE
 Help configuring macvtap interface

### ISSUE THREAD

**Issue by illode** [astro/microvm.nix#106]
I've been trying to get macvtap working for a bit now, but the generated interface/ip always points to the host.
The vm config:
```nix
let 
  name = "test-vm";
in { pkgs, microvm, ... }: {
  imports = [ microvm.host ];
  
  microvm.vms.${name} = {
    config = {
      #imports = [ microvm.microvm ];
      networking.hostName = name;
      networking.firewall.enable = false;
      services.openssh = {
        enable = true;
        settings.PermitEmptyPasswords = "yes";
        settings.PermitRootLogin = "yes";
      };
      users.users.root.password = "";
  
      microvm.hypervisor = "cloud-hypervisor";
      microvm.shares = [{
        source = "/nix/store";
        mountPoint = "/nix/.ro-store";
        tag = "ro-store";
        proto = "virtiofs";
      }];
      microvm.interfaces = [{
        type = "macvtap";
        id = "${name}-macvtap";
        mac = "02:00:00:00:00:01";
        macvtap = {
          link = "ConnectX3";
          mode = "bridge";
        };
      }];
      system.stateVersion = "22.11";
    };
  };
}
```
The ConnectX3 link is defined in a separate file:
```nix
{
  systemd.network.enable = true;
  
  systemd.network.links."10-ConnectX3" = {
    matchConfig.MACAddress = "ec:0d:9a:19:d9:a0";
    linkConfig.Name = "ConnectX3";
  };
}
```
The `microvm` arg is passed from `flake.nix` with `specialArgs.microvm = microvm.nixosModules;`

`ip link` on the host:
```
❯ ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: ConnectX3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether ec:0d:9a:19:d9:a0 brd ff:ff:ff:ff:ff:ff
41: test-vm-macvtap@ConnectX3: <BROADCAST,MULTICAST,ALLMULTI,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 500
    link/ether 02:00:00:00:00:01 brd ff:ff:ff:ff:ff:ff
```
`ip -4 a` on the host:
```
❯ ip -4 a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: ConnectX3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    inet 10.0.1.40/24 brd 10.0.1.255 scope global dynamic noprefixroute ConnectX3
       valid_lft 6924sec preferred_lft 6024sec
41: test-vm-macvtap@ConnectX3: <BROADCAST,MULTICAST,ALLMULTI,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 500
    inet 10.0.1.224/24 brd 10.0.1.255 scope global dynamic noprefixroute test-vm-macvtap
       valid_lft 6775sec preferred_lft 5875sec
```
I can't run either command on the guest since I can't access it.

Running ssh root@10.0.1.224 from any machine on the LAN tries to log in to the host not the guest.

The docs make it seem like I don't need to do any additional network setup outside of `microvm.interfaces`, but I also tried using #80 as a reference which didn't help.

The only other thing worth noting is that the docs seem to imply the guest needs `microvm.microvm` to included, but that gives me errors about things being defined multiple times so I commented it out.

**Comment by astro** [comment]
The guest's address must not be configured on the host side of the tap interface. Leave it without addresses. You won't even need link-local addresses (`fe80::/64`). `10.0.1.224/24` has to be configured in the guest instead.

> The only other thing worth noting is that the docs seem to imply the guest needs microvm.microvm to included, but that gives me errors about things being defined multiple times so I commented it out.

You are using non-flake declarative VMs which got recently merged. We may need to update docs and examples accordingly.

**Comment by astro** [comment]
Disable DHCP for `test-vm-macvtap@ConnectX3`

Not sure if that fixes the VM's connectivity. I guess it will do DHCP by default? Did you know the `ping ff02::1%ConnectX3` trick?
