### ISSUE TITLE
How to use systemd-networkd for guest network creation?

### ISSUE THREAD

**Issue by spacekitteh** [astro/microvm.nix#109]
I'm trying to set up a TUN interface with a declarative guest in my flake. Since `mktuntap` is used to create the interface, I cannot match on it with systemd rules. How can I manage guest networking decoratively with systemd?

**Comment by astro** [comment]
Statically configuring tap interfaces wouldn't allow `/var/lib/microvms` to be dynamic and stateful.

Did you see the [example network section in the handbook](https://astro.github.io/microvm.nix/simple-network.html#a-bridge-to-link-tap-interfaces)?

```nix
systemd.network = {
  networks."11-microvm" = {
    matchConfig.Name = "vm-*";
    # Attach to the bridge that was configured above
    networkConfig.Bridge = "microvm";
  };
};
```

systemd-networkd knows three configuration categories:
- `link` is for preexisting interfaces
- `netdev` is for creating virtual interfaces, which we don't use
- `network` is for address and routing configuration, which you can use like in the example above

**Comment by spacekitteh** [comment]
Is that not part of the host expression, though, not the guest? How can the /guest/ configure whether to, say, use DHCP or not?

**Comment by astro** [comment]
Networking must be configured on both host and guests.

[`networking.interfaces.<name>.useDHCP`](https://search.nixos.org/options?channel=23.05&show=networking.interfaces.%3Cname%3E.useDHCP&from=0&size=50&sort=relevance&type=packages&query=usedhcp)

**Comment by astro** [comment]
Can we close this issue?

**Comment by astro** [comment]
See also: #116
