### ISSUE TITLE
Deploying imperatively

### ISSUE THREAD

**Issue by MrFoxPro** [astro/microvm.nix#119]
Hello, thank you for this project. 
My goal is to decouple applications from host configuration. Using containers, I can build image and push it to host. 
Is it possible to copy built microVM to host, e.g. from CI, without attaching to remote flake?

I think it's possible to use nix copy, but how to activate it on Host then? Wrap it to something like buildEnv?

**Comment by MrFoxPro** [comment]
I think it's possible to use `nix copy`, but how to activate it on Host then?

**Comment by MrFoxPro** [comment]
I wrote script for nushell:
```nu
let name = "my-microvm"
let host = "mary-aeza"

nu -c $"nix build .#($name) -o ./result"
let image = (readlink ./result)
let dir = $"/var/lib/microvms/($name)"

nix copy --to $"ssh://($host)" ./result 

$"
rm -rf ($dir)/
mkdir -p ($dir)
ln -s ($image) ($dir)/current

chown :kvm -R ($dir)
chmod -R a+rX ($dir)
chmod g+w ($dir)

mkdir -p /nix/var/nix/gcroots/microvm
rm -f /nix/var/nix/gcroots/microvm/($name)
ln -s ($dir)/current /nix/var/nix/gcroots/microvm/($name)
rm -f /nix/var/nix/gcroots/microvm/booted-($name)
ln -s ($dir)/booted /nix/var/nix/gcroots/microvm/booted-($name)

systemctl restart microvm@($name).service
" | ssh "mary-aeza" "bash -s" 
```
Seems like it's working for updating microvm

**Comment by astro** [comment]
Great that this can be figured out without my help. We do something very similar over here: https://gitea.c3d2.de/c3d2/nix-config/src/branch/master/packages.nix#L163

Should this go into the handbook?

**Comment by MrFoxPro** [comment]
> Great that this can be figured out without my help. We do something very similar over here: https://gitea.c3d2.de/c3d2/nix-config/src/branch/master/packages.nix#L163
> 
> Should this go into the handbook?

Yes, thanks for hint, `nix store diff-closures ./old ./current` could be useful. Now I will figure out how application work in microvms =)
Regarding docs: I want to help, but I'm so overloaded with work and also not so good at English. Let this issue be open, maybe I return back to suggest article

**Comment by MrFoxPro** [comment]
Want to add that with this way `microvm` CLI won't work because it wants `flake` file to read flake source from, but, as I can understand, I can do all next work directly with systemd services

**Comment by MrFoxPro** [comment]
Also interested if there are some registries for microVM that I can use for versikned deployments

**Comment by MrFoxPro** [comment]
> > Also interested if there are some registries for microVM that I can use for versioned deployments
> 
> You don't mean `nix registry add microvm github:astro/microvm.nix`, right?

No, I mean something like docker-registry. Currently I'm creating files for previous deployemnt and new one, then, when deployment occurs, I swap it (in CI)

**Comment by astro** [comment]
I haven't used the docker registry much but the vague idea sounds interesting. Can you please describe in more detail what part of your Nix-based workflow that would change?

**Comment by astro** [comment]
I added the solution to the original issue to the faq in 2f15c1a.

Registry ideas still excite me. Please elaborate.
