### ISSUE TITLE
Minimal image / configuration?

### ISSUE THREAD

**Issue by MrFoxPro** [astro/microvm.nix#120]
I noticed that by default there are some dependencies like Xlibs, pulseaudio that are improted in VM. Is it possible to avoid it? Is there any recommended minimal configuration/preset?

**Comment by astro** [comment]
I am constantly wondering how much `lib.mkDefault` we should put into our module. While most people use microvm.nix for server usage, there had been a request for the cloud-hypervisor graphics feature before (#83).

**Comment by phaer** [comment]
Same question works for the host side; It's currently pulling in things like gstreamer, with all its dependencies, bluez, ffmpeg, sox, etc into my hosts closure even though that one exclusively runs non-graphical hosts.

Ideally we could have a "headless" variant toggled via config option or so? No big deal if not, it justs worsens eval-time as well as transfer times of my system closure

**Comment by astro** [comment]
@phaer Which hypervisor has these dependencies? Probably qemu?

We could override qemu with `gtkSupport = false` but that would mean you can't download it from cache.nixos.org.

**Comment by astro** [comment]
@MrFoxPro Did you know NixOS option `environment.noXlibs`?

@phaer Either use a hypervisor without a graphical frontend, or override `qemu` with `pkgs.qemu_test` which seems to work but doesn't look like it's absolutely 100% future-proof.

**Comment by astro** [comment]
I have retained these suggestion in the faq. 2f15c1a

**Comment by astro** [comment]
Please take note of the new `microvm.optimize.enable` setting that is enabled by default: #146
