### ISSUE TITLE
Need better document about writableStoreOverlay

### ISSUE THREAD

**Issue by luochen1990** [astro/microvm.nix#124]
1. The [Document](https://astro.github.io/microvm.nix/declarative.html) about `microvm.writableStoreOverlay = true;` is not working.
2. What is the meaning of [writableStoreOverlay](https://github.com/astro/microvm.nix/blob/main/nixos-modules/microvm/options.nix#L321C1-L330C7) if it is set to `null` ?

**Comment by astro** [comment]
Thank you very much for reporting. I wouldn't have caught this myself.

1. 132433aaad9e2fec339b9f97849bfb627106ca00

   I removed the wrong config completely for a more minimal example.
2. fdbea17f1dad256aa08aead75449d2f5fdc17ef7

   `writableStoreOverlay == null` means a truly read-only /nix/store
