### ISSUE TITLE
NixOS Generators-Like Functions?

### ISSUE THREAD

**Issue by brotherdust** [astro/microvm.nix#130]
I use NixOS-generators quite a bit to build VM's for my Proxmox cluster. The VM's tend to be pretty heavy and it seems like microvm would be a good fit as an alternative. Is it possible to just generate a VMA or QCOW image of a microvm?

How hard would it be to integrate microvm into nixos-generators do you think?

Thanks much!

**Comment by astro** [comment]
Proxmox preselects the Hypervisor for you (qemu). There isn't much point in using this flake other than to generate the rootfs which nixos-generators does fine already.

**Comment by brotherdust** [comment]
@astro , thank you for the quick reply. I appreciate your thoughts on this and I think you are correct.

As I am refining the requirements for my project, it would seem NotOS is a closer fit. As it's made for containers, I'll have to do some modifications to make it work as a VM.

I digress. Again, thank you!
