### ISSUE TITLE
running aarch64 qemu fails with no option group 'sandbox'

### ISSUE THREAD

**Issue by furioncycle** [astro/microvm.nix#135]
I was wanting to build an **aarch64 linux vm** on my host which is "x86-64-linux" . 

I grabbed the template using  `nix flake init -t github:astro/microvm.nix` and changed the system string to `aarch64-linux` and run the following command

```bash
nix run .#nixosConfigurations.my-microvm.config.microvm.declaredRunner
```
once it finished downloading and configuring. I got the following error once it tried to start up the vm.

```bash 
qemu-system-aarch64: -sandbox on: There is no option group 'sandbox'
```
checking qemu-system-aarch64's help menu their is that option, is their a reason why this would fail to boot? 

I am able to boot it if I have my hosts system setting.

**Comment by astro** [comment]
Unfortunately, my RPi4 appears overwhelmed by just anything I throw at it.

Maybe @mikatammi can help regarding aarch64?

**Comment by mikatammi** [comment]
Trying to read throughfully through the initial message. So @furioncycle are you trying to emulate aarch64-linux on top of x86_64-linux? Or trying to cross-compile a virtual machine from x86_64-linux build machine so that it would run on aarch64-linux host?

**Comment by mikatammi** [comment]
I think the scope of the project is more virtualization than emulation, but it would probably be possible to emulate microvms built for different host architectures with qemu as well. However different set of flags is needed for QEMU if you want to do emulation

**Comment by furioncycle** [comment]
> Trying to read throughfully through the initial message. So @furioncycle are you trying to emulate aarch64-linux on top of x86_64-linux? Or trying to cross-compile a virtual machine from x86_64-linux build machine so that it would run on aarch64-linux host?

I am trying to emulate aarch64-linux.

**Comment by furioncycle** [comment]
> I think the scope of the project is more virtualization than emulation, but it would probably be possible to emulate microvms built for different host architectures with qemu as well. However different set of flags is needed for QEMU if you want to do emulation

That makes sense and if it is outside of the scope of this project, it is no problem. I can look at what I would need for emulation with qemu.
