### ISSUE TITLE
Relax microvm.shares.*.source type constraint

### ISSUE THREAD

**Issue by figsoda** [astro/microvm.nix#138]
The current option has `type = path;`, which doesn't allow relative paths like `"."`, which could be useful

this patch works for my specific use case, but can break other valid options, since `types.str` uses `isString` instead of `isStringLike`

```patch
--- a/nixos-modules/microvm/options.nix
+++ b/nixos-modules/microvm/options.nix
@@ -257,7 +257,7 @@ in
             description = "Socket for communication with virtiofs daemon";
           };
           source = mkOption {
-            type = path;
+            type = str;
             description = "Path to shared directory tree";
           };
           mountPoint = mkOption {
```

**Comment by figsoda** [comment]
opened https://github.com/NixOS/nixpkgs/pull/256353 so we can use `stringLike` and not break backwards compatibility

**Comment by astro** [comment]
`str` or `nonEmptyStr` works for me. I actually want `source` to be a string, never a store path.
