### ISSUE TITLE
doc: what is the purpose of wayland-proxy in the graphics example

### ISSUE THREAD

**Issue by colemickens** [astro/microvm.nix#140]
Hi, hope you don't mind a question in the Issues.

I'm somewhat familiar with the `wayland-proxy-virtwl` project -- I use it to run a throwaway Xwayland instance to run some X11 apps in Sway when I have Xwayland disabled globally.

However, I can't figure out what the purpose of using it in the VM is? Is it an optimization to allow more performant graphics in the VM, or for hypervisors that don't support graphics natively?

If someone can shed some light, I can add some comments and send a PR to document it inline in the graphics example.

**Comment by astro** [comment]
Background: #83 Happy to read your thoughts about graphics. PRs are very welcome!

I have been wondering if waypipe over vsock wouldn't be more portable across different hypervisors, but I haven't gotten around to try that...
