### ISSUE TITLE
error: creating directory  /nix/store/.links': Read-only file system

### ISSUE THREAD

**Issue by GTrunSec** [astro/microvm.nix#15]
Reproduced by:

```
microvm -c example
error: creating directory '/nix/store/.links': Read-only file system
```

I got the same issue with the home-manager service in microVMs as well.

**Comment by astro** [comment]
Just for clarification: this is *not* the `.#vm` example that runs in a MicroVM now, still with a read-only /nix/store?

**Comment by GTrunSec** [comment]
Yeh, still with a read-only /nix/store. I needed to deploy the home-manager services in MicroVM, and the service log outputted this error message. I have no idea why.

**Comment by astro** [comment]
These MicroVMs are built from the host or some other system. They always run with a read-only /nix/store so far.

I think that's a sensible and secure default for isolation with MicroVMs.

Having a writable /nix/store so you can build packages is a valid use-case. We should take a look at how the usual NixOS VMs do it...
