### ISSUE TITLE
`graphics` example fails to start, args passed to cloud-hypervisor fail validation

### ISSUE THREAD

**Issue by vivlim** [astro/microvm.nix#166]
Trying to run the graphics example with `nix run .#graphics neverball` causes this error to be printed:

```
Error parsing config: Error validating configuration: Using vhost-user requires using shared memory or huge pages
```

It seems related to https://github.com/astro/microvm.nix/commit/42ac0e76908f028443eb55602b974b7e0f0f2add, if I set `shared = "on";` the VM is able to start (although I then hit some other problem that seems unrelated)

**Comment by astro** [comment]
Thank you for reporting this issue. I hope to have fixed this in 716c2dbec73ca57189d5346c348fe62f9c84d69b.
