### ISSUE TITLE
Could this project be used with public cloud?

### ISSUE THREAD

**Issue by takeda** [astro/microvm.nix#168]
As I understand, the idea behind this project is to provide functionality similar to nixos-container that utilizes hypervisors.

In public cloud the traditional instances are already VMs. I'm wondering if this project could be used to create images to be for example run directly in EC2. If that's possible, how I could accomplish this? Are there other projects that might be targeting the idea?

Basically I'm hoping for a way to create a microvm's that contain just my application + essential components to boot such VM in public cloud.

**Comment by astro** [comment]
I think you'll be better served with https://github.com/nix-community/nixos-generators

**Comment by takeda** [comment]
@astro I'm aware od nixos-generators, but I was hoping for minimal image, for example running on firecracker. The images generated by nixos-generators are still full blown NixOS.

**Comment by astro** [comment]
Do you want to run on EC2 or on Firecracker?

For a minimal NixOS, have a look at:
- [our optimization module](https://github.com/astro/microvm.nix/blob/main/nixos-modules/microvm/optimization.nix)
- [NixOS' minimal profile](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/profiles/minimal.nix)

**Comment by takeda** [comment]
@astro I assumed that since firecracker comes from Amazon and they are using it also for some of their services like lambda, then it could be used in their EC2 VMs too.

After your response, and looking more at it, it looks like the way they expect it to be used is to provision their "metal" instance and use it in similar wy. I was hoping I could run it in traditional EC2 VM and benefit of only paying for what I actually use. It's a shame they don't allow that.

Anyway, thank so much for your links, that still helps a lot.
