### ISSUE TITLE
No 'PCI' bus found for device 'virtio-rng-pci'

### ISSUE THREAD

**Issue by groulot** [astro/microvm.nix#178]
I run NixOS 23.11 in a virtualbox VM.

Following the documentation, an error happens when trying to run my-microvm. If did 
`nix registry add microvm github:astro/microvm.nix`, `nix flake init -t microvm` and then `nix run .#my-microvm`

`
$ nix run .#my-microvm
warning: Git tree '/home/groulot/infra' is dirty
qemu-system-x86_64: -device virtio-rng-pci: No 'PCI' bus found for device 'virtio-rng-pci'
`

Removing the example 9p share bellow in the flake fixes the error. The MicroVM starts and runs correctly:
`
shares = [ {
  proto = "9p";
  tag = "ro-store";
  source = "/nix/store";
  mountPoint = "/nix/.ro-store";
} ];
`

Is there anything I missed that I should have done to make it work ?

**Comment by astro** [comment]
Ouch, that is a consequence of disabling ACPI in c39a472523d3c99ddfa88df62223a21b19793490 as required by #171.

Does the machine boot for you if you replace `s/acpi=off/acpi=on/` in `lib/runners/qemu.nix` in your local checkout when running nix with `--override-input microvm git+file:///.../microvm.nix`?

**Comment by astro** [comment]
Actually, breaking PCI is worse than #171 so I'm reverting that fix.
