### ISSUE TITLE
question: autoscale?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [astro/microvm.nix#182]
in presentation you mentioned autoscale prototype.

do you have presentation about it or some blog post?

very intresting, nix needs that.

many things going on:

- https://fly.io/blog/carving-the-scheduler-out-of-our-orchestrator/
- nomad
- abstraction on each cloud autoscaler?
- using k8s autoscaler as library?
- https://github.com/googleforgames/agones/

something which can eventually used by https://github.com/hercules-ci/support/issues/14 may be

**Comment by astro** [comment]
Yes, but it's all experimental and unfinished:
- https://blogs.c3d2.de/~/Astroblog/NixOS%20Clusters
- https://github.com/astro/skyflake

**Comment by dzmitry-lahoda** [comment]
cool. read it.
