### ISSUE TITLE
Generating random MAC address

### ISSUE THREAD

**Issue by jim3692** [astro/microvm.nix#190]
In my configuration I am implementing options to abstract the creation of VMs and containers. One of the issues I was facing was the MACs for my TAPs that connect to my bridges. I want them to be generated automatically.

So I wrote this function that creates random files, and gets the hex characters from their paths, as I could not find a better way to generate random strings. Of course, this is not an optimal solution and may result in MAC collisions, but I wanted to share in case anyone else wants to take the risk:

```nix
{ vmName }:
  let
    getFile = { }: lib.toFile vmName "";

    files = [
      (getFile { })
      (getFile { })
      (getFile { })
      (getFile { })
      (getFile { })
      (getFile { })
      (getFile { })
      (getFile { })
    ];

    filesHexValues = lib.map (s:
      let
        nonHexValues =
          lib.filter (x: lib.isString x && x != "") (lib.split "[0-9a-f]" s);
        replaceWith = lib.replicate (lib.length nonHexValues) "";
      in lib.replaceStrings nonHexValues replaceWith s) files;

    hexString = lib.concatStrings filesHexValues;

    hexString8Chars = lib.substring 0 8 hexString;

    splitHexToPairs = (lib.foldl' ({ idx, result }:
      _:
      if (lib.mod idx 2) == 0 then {
        idx = idx + 1;
        result = result ++ [ (lib.substring idx 2 hexString8Chars) ];
      } else {
        idx = idx + 1;
        result = result;
      }) {
        idx = 0;
        result = [ ];
      } (lib.replicate 8 "")).result;

    mergedPairs = lib.concatStringsSep ":" splitHexToPairs;
  in "02:00:" + mergedPairs;
  ```

**Comment by astro** [comment]
I've got some alternative MAC address generation over here: https://github.com/astro/skyflake/blob/main/default-customization.nix#L4

Do you have any follow-up in mind so that this ticket can be closed eventually?

**Comment by jim3692** [comment]
I did not spot the `hashString` function in builtins. This can be closed. I just opened it as a note for future readers, because I could not find any similar discussions.
