### ISSUE TITLE
Mounting /nix/store via 9p

### ISSUE THREAD

**Issue by GTrunSec** [astro/microvm.nix#20]
I think it's time to talk about the solution of migrating v9. I got a lot of pain from squashfs experience something like you [mentioned](https://github.com/astro/microvm.nix/issues/3#issuecomment-939291157) before. So, I would like to request this feature to improve the performance and use experience.

**Comment by astro** [comment]
Skipping squashfs creation would be very nice for development speed. I still would like to keep the read-only squashfs as an option for production usage.

virtiofs is supposed to be faster than 9p, so ideally we support both.

There is at least one hypervisor that requires a root disk. Perhaps a dummy will work.

**Comment by GTrunSec** [comment]
> read-only squashfs as an option for production usage.
That's reasonable, and either virtiofs or 9p support is good for me.  I just need a really faster developing environment to test a bunch of services. once everything goes well that the  squashfs would be an option for reproduction.

**Comment by GTrunSec** [comment]
By the way, Do you have time to implement this feature? I have a 200$ bonus for your this work.

**Comment by astro** [comment]
Tempting! Is there a deadline? I'm going to be largely unavailable next week.

**Comment by GTrunSec** [comment]
Actually, there is no deadline, It's up to you. Of course, if it can be implemented as soon as possible, that would be happy for my personal expectation。

**Comment by astro** [comment]
How do we design understandable `options` depending on:

- read-only store in rootfs image
- read-only store from the host

- no writable overlay
- writable overlay on volume
- writable overlay on share

Anything I have not thought of?

**Comment by GTrunSec** [comment]
looks good for me, go ahead.

**Comment by astro** [comment]
This works now!

**Comment by GTrunSec** [comment]
Thanks, Good job
