### ISSUE TITLE
NixOS hardened profile - erofs fails to mount due to blacklist inheritance

### ISSUE THREAD

**Issue by bolives-hax** [astro/microvm.nix#202]
when building vm's for

- [x] cloud-hypervisor
- [x] qemu
- ??? firecracker <well that rn doesn't work as a mere runner I gotta look into that in a bit>
- [x] crosvm 
- [x] kvmtool
- [x] stratovirt

utilizing:
```nix
modules = [
  ({modulesPath}: { imports = [ "${modulesPath}/profiles/hardened.nix" ]; })
];
```

this causes the erofs-store image to not be mounted, as 
 (currently) [https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/profiles/hardened.nix#L68](url) introduces a

```nix
boot.blacklistedKernelModules = [ <...> "erofs" <...> ];
```

statement saying "# Old or rare or insufficiently audited filesystems. In action it may look like:

![image](https://github.com/astro/microvm.nix/assets/125610892/ae38008d-97f3-4b7e-a2d6-69b9a31c6d9d)

I am aware that the NixOS hardened profile blacklisting a kernel module that is used during the boot process is not exactly the fault of microvm.nix, but I think it would still be cool to address it in some way as otherwise the hardening profile works without any issues.

Part of the issue is the way the hardening profile/module provides boom.blacklistedKernelModules, because once it adds something to it I don't see how we would remove it again without running into an infinitive recursion problem OR using lib.mkForce which has its obvious drawbacks as well. I'm currently thinking of a way on how to integrate this nicely into a fork I made but I haven't solved the issue yet.

As for now my idea is to basically instead of directly importing nixos/modules/profiles/hardened.nix if sth like ```config.microvm.guestSystemHardening``` would be set, one could while hacky import it via a let statement and the import keyword first. Then deconstructruct the option and append it to

```nix
# modules that consume boot time but have rare use-cases
boot.blacklistedKernelModules = [
  "rfkill" "intel_pstate"
] ++ lib.optional (!config.microvm.graphics.enable) "drm";
```

in line [https://github.com/astro/microvm.nix/blob/d227a91e7524db9367d0c4f2ed0656ea944bcbe7/nixos-modules/microvm/system.nix#L36](url)

**Comment by bolives-hax** [comment]
```nix
testHardendNixpkgs = (nixpkgs.lib.nixosSystem {
  system = "x86_64-linux";
  modules = [
    microvm.nixosModules.microvm
    ({modulesPath,lib,...}: with lib; {
      #imports = [ "${modulesPath}/profiles/hardened.nix" ];
      users.users.root.password = "root";

      microvm = {
        mem = 1024;
        vcpu = 2;
        hypervisor = "cloud-hypervisor";
      };

      boot.blacklistedKernelModules = mkForce [
        # Obscure network protocols
        "ax25"
        "netrom"
        "rose"

        # Old or rare or insufficiently audited filesystems
        "adfs"
        "affs"
        "bfs"
        "befs"
        "cramfs"
        "efs"
        # the erofs blacklist in question we can't have if we want
        # a bootable system
        #"erofs"
        "exofs"
        "freevxfs"
        "f2fs"
        "hfs"
        "hpfs"
        "jfs"
        "minix"
        "nilfs2"
        "ntfs"
        "omfs"
        "qnx4"
        "qnx6"
        "sysv"
        "ufs"
      ];

    })
  ];
}).config.microvm.declaredRunner;
```

here is an example of how i currently bypass the issue in a test config but that would ignore `"rfkill" "intel_pstate" "drm"` that are blacklisted by microvm unless i were to add them to the list but maintaining static/hardcoded lists seem like back practice and id rather want the module/options logic to decide on the actual blacklists

**Comment by astro** [comment]
Thank you. The hardened profile is a very valid use-case because virtualization is used for security reasons.

One workaround would be setting `microvm.storeDiskType = "squashfs"` which is not blacklisted in the hardened profile. We can change the default by testing the contents of `config.boot.blacklistedKernelModules`. Would that work for you?

**Comment by bolives-hax** [comment]
> Thank you. The hardened profile is a very valid use-case because virtualization is used for security reasons.
> 
> One workaround would be setting `microvm.storeDiskType = "squashfs"` which is not blacklisted in the hardened profile. We can change the default by testing the contents of `config.boot.blacklistedKernelModules`. Would that work for you?




> The check I added would still select erofs if you import the hardened profile but override `boot.blacklistedKernelModules` with your own list in case you don't want squashfs.

Yes that would work, thanks for taking the time to review this this for sure solves the problem in a way I wouldn't know how to do better. Thanks!
