### ISSUE TITLE
Add `securityModel` option to 9P shares for QEMU

### ISSUE THREAD

**Issue by rmgaray** [astro/microvm.nix#206]
Hello! I would like to thank you first for your project, which I find very friendly for a virtualization newbie like myself.

I am trying to set up a VM with a share to be mounted in `/home/myuser`. But in order to have this share as a usable home folder for `myuser`, I need to change its permissions. I noticed that all shares are mounted in `qemu` using the `none` security model, which automatically mounts all the shares as `root` (let me know if I am mistaken about this).

I feel for my use-case having `mapped` would be better.

So I forked the repo and added one :) . I would like to know if I did well or there is perhaps an easier way of doing this.

**Comment by astro** [comment]
Do you mind opening a Pull Request for review?

**Comment by rmgaray** [comment]
Not at all.
