### ISSUE TITLE
Running MicroVM on a Proxmox host

### ISSUE THREAD

**Issue by romner-set** [astro/microvm.nix#208]
First of all, sorry if this is offtopic since it's more of a question than an issue – I'd put this in the discussions section if there was one.

Basically, I currently have a homelab running Proxmox with Debian- and Ubuntu-based server LXCs and VMs that are all declaratively managed through Terraform + bash scripts and I'm looking to migrate them all to NixOS. Now, if that was everything I ran on the server I'd likely switch to NixOS with MicroVMs in a heartbeat, but I also run desktop non-NixOS Linux and Windows VMs with passed-through GPUs and temporary misc. VMs for testing out ISOs and stuff, all of which is either unsupported in MicroVM (to my knowledge), benefits heavily from the Proxmox WebUI, or both.

So I'm thinking, how stupid of an idea would it be to keep running all of the desktop/temporary VMs in Proxmox, install nix on the host and run server MicroVMs alongside the Proxmox-managed VMs? Looking at [this issue](https://github.com/astro/microvm.nix/issues/169) it seems like it should work, but I'm not sure if it'd work well, or if there's any better or easier solution that'd make this not even worth attempting.

**Comment by astro** [comment]
Should work. Also, see https://nixos.paris/@julienmalka/111954275881949393

For alternatives to Proxmox on NixOS, consider libvirt or virtualbox.

**Comment by romner-set** [comment]
> Should work. Also, see https://nixos.paris/@julienmalka/111954275881949393

Thanks, that looks very promising!

> For alternatives to Proxmox on NixOS, consider libvirt or virtualbox.

Virtualbox doesn't use KVM and so is way slower, plus lacks support for PCI passthrough AFAIK. Libvirt is a solid option, but it lacks the management interface so spinning up temporary VM takes way longer than it would on Proxmox... I did find some WebUIs, but they're all either incredibly outdated or really hard to install on NixOS. The homelab isn't running anything critical on the server side of things so I guess I'll just try it and see what happens, thanks for the help.
