### ISSUE TITLE
Doc: Confusing paragraph on landing page

### ISSUE THREAD

**Issue by ShalokShalom** [astro/microvm.nix#211]
Hi there :)

I love and enjoy your product. I think the docs could get a bit more love, and the third paragraph in this example looks totally out of place for me: 

![Screenshot__](https://github.com/astro/microvm.nix/assets/6344099/1f5ff597-adfd-416e-8d68-8b98db9a911f)

You go on to lay out the different benefits and disadvantages of both the Container and VM approach, and I wait for what microvm does different in that aspect, to solve this specific tradeoff. 

And the paragraph ignores that entirely, and simply goes on to rave about some random security feature, that has nothing to do with the expectations as reader. 

I strongly suggest to move that part to the bottom, and make it the last paragraph.

**Comment by astro** [comment]
Thank you very much for sharing your opinion! I am very happy to improve the documentation, for which your description was really helpful.

I agree that this paragraph was a bit off in that section. I replaced it with a more appropriate blurb. However, I think that the file-system isolation isn't a random feature but actually belongs to the Compartmentalization section.

**Comment by ShalokShalom** [comment]
> microvm.nix is a tool that helps you building the guest's OS and running ways that are easier than writing a Dockerfile, once you know how to put a NixOS config into a flake.nix file.

running ways?

**Comment by astro** [comment]
Oops. Writing prose is hard, let's go write code instead! ;-)

**Comment by ShalokShalom** [comment]
Code is prose ;)
