### ISSUE TITLE
Configured host kernel version not used for microVMs

### ISSUE THREAD

**Issue by jpds** [astro/microvm.nix#215]
I've started to migrate hosts to the new LTS kernel with:

```nix
  boot.kernelPackages = pkgs.linuxPackages_6_6;
```

However, the microVMs are still using the default 6.1 release:

```
microvm     3155 18.9  0.4 5484940 543168 ?      Ssl  15:03   0:16 microvm@prometheus --cpus boot=4 --watchdog --console null --serial tty --kernel /nix/store/1vpwxv3cwidf0spag9gfdgqwd21q5f44-linux-6.1.82-dev/vmlinux --initramfs /nix/store/658yg4vbh903wnz2ybvch5bfyyddf2sb-initrd-linux-6.1.82/initrd --cmdline ...
```

**Comment by astro** [comment]
I am doing the same but in the microvm's NixOS configuration, not in the host configuration.

**Comment by jpds** [comment]
Ah, I see. The wording of the https://github.com/astro/microvm.nix/blob/0e2223d8fd459725850bd9aff7e9d68ec329769a/nixos-modules/microvm/options.nix#L59-L64 option seemed to suggest it would be inherited.
