### ISSUE TITLE
Issue mounting shares in sysroot

### ISSUE THREAD

**Issue by IogaMaster** [astro/microvm.nix#234]
When defining shares in microvm.shares, the sysroot in the systemd initrd fails to mount them.

```nix
    microvm = {

      shares = [
        {
          # Without sharing the hosts /nix/store, the images will be MASSIVE.
          tag = "ro-store";
          source = "/nix/store";
          mountPoint = "/nix/.ro-store";
        }
      ];
    };

```

Then the ro-store mount fails. Causing the system to be unbootable.

**Comment by astro** [comment]
Which hypervisor? Do you run it in a systemd unit? The share's `proto` is the default `"9p"`?

**Comment by IogaMaster** [comment]
`cloud-hypervisor`, it also failed with `virtiofs` proto.

**Comment by astro** [comment]
cloud-hypervisor supports only virtiofs but not 9p. virtiofs requires a separate daemon which is started by a systemd unit. If the microvm is run interactively, the daemon needs to be running.

Does that help you?

**Comment by IogaMaster** [comment]
I will use qemu if i have to, however in my testing cloud-hypervisor is significantly faster. Even over firecracker

**Comment by IogaMaster** [comment]
Okay, it appears that I am not very smart, or careful in my reading lol.
I was using the microvm guest module on the host, assuming that it was like a default module that other projects use.
After removing these issues are no longer present.
