### ISSUE TITLE
guest linux kernel binary release?

### ISSUE THREAD

**Issue by milahu** [astro/microvm.nix#3]
compiling a custom kernel takes ... forever

```
$ nix run microvm#firecracker-example
```

can we use a binary relase? or cache the build on cache.nixos.org?

use case: package an untrusted binary as firecracker microVM
the install should take 5 minutes, not 5 hours (roughly speaking)

~~edit: of course, the binary kernel must be a reproducible build~~
edit: took 8 hours to compile the kernel on my 2x2.4GHz cpu
edit: ideally, the binary kernel should be a reproducible build

**Comment by astro** [comment]
You are right.

That's the config we need from the kernel: https://github.com/astro/microvm.nix/blob/main/nixos-modules/microvm.nix#L20

Also, mksquashfs is taking long. Mounting /nix/store via 9p or virtiofs would be much faster, also saving disk space.

**Comment by astro** [comment]
Good idea but that kernel will probably not fit all hypervisors. Haven't yet tried though.

**Comment by milahu** [comment]
> that kernel will probably not fit all hypervisors

personally, i need only firecracker

here is a start ... [linux-firecracker/default.nix](https://github.com/milahu/nur-packages/blob/master/pkgs/linux-firecracker/default.nix)

**Comment by milahu** [comment]
trying to set kernel via nixosConfig

```nix
# microvm.nix/flake.nix
                nixosConfig = {
                  boot.kernelPackages = pkgs.linuxPackagesFor (pkgs.callPackage ./pkgs/linux-firecracker.nix {});
```

 gives ```error: The option `boot.kernelPackages' has conflicting definition values```

```nix
# microvm.nix/flake.nix
                  modules = [
                    self.nixosModules.microvm   # boot.kernelPackages is set here
                    nixosConfig
                  ];
```

```nix
# microvm.nix/nixos-modules/microvm.nix
  boot.kernelPackages = pkgs.linuxPackages_latest.extend (self: super: {
    kernel = super.kernel.override {
      extraConfig = ''
```

naive solution:
add module `nixosConfig` first, then `self.nixosModules.microvm`
in `self.nixosModules.microvm`,
set `boot.kernelPackages` only if it was not set by `nixosConfig`

**Comment by milahu** [comment]
in `microvm.nix/nixos-modules/microvm.nix`,
some `extraConfig` settings are different than in the firecracker config

<details>

```diff
--- /nix/store/m1gzg956q46vmm0692s9140ay8hc0gfv-microvm-kernel-x86_64.config
+++ /nix/store/bnxjzgw2fsxd6jh85yj3zpbvnmc0ylip-linux-firecracker.config
@@ -199,7 +199,7 @@
 CONFIG_SYSCTL_EXCEPTION_TRACE=y
 CONFIG_HAVE_PCSPKR_PLATFORM=y
 CONFIG_BPF=y
-# CONFIG_EXPERT is not set
+CONFIG_EXPERT=y
 CONFIG_UID16=y
 CONFIG_MULTIUSER=y
 CONFIG_SGETMASK_SYSCALL=y
@@ -1094,7 +1094,7 @@
 # CONFIG_BATMAN_ADV is not set
 # CONFIG_OPENVSWITCH is not set
 CONFIG_VSOCKETS=y
-CONFIG_VIRTIO_VSOCKETS=y
+CONFIG_VIRTIO_VSOCKETS=m
 CONFIG_VIRTIO_VSOCKETS_COMMON=y
 # CONFIG_NETLINK_DIAG is not set
 CONFIG_MPLS=y
@@ -1885,7 +1885,7 @@
 CONFIG_QUOTACTL=y
 CONFIG_QUOTACTL_COMPAT=y
 # CONFIG_AUTOFS4_FS is not set
-# CONFIG_FUSE_FS is not set
+CONFIG_FUSE_FS=y
 CONFIG_OVERLAY_FS=y
 # CONFIG_OVERLAY_FS_REDIRECT_DIR is not set
 # CONFIG_OVERLAY_FS_INDEX is not set
@@ -2528,3 +2528,9 @@
 CONFIG_ARCH_HAS_UACCESS_FLUSHCACHE=y
 CONFIG_SBITMAP=y
 # CONFIG_STRING_SELFTEST is not set
+CONFIG_PVH=y
+CONFIG_VIRTIO_FS=y
+CONFIG_VIRTIO_PCI=y
+CONFIG_VIRTIO_PCI_LIB=y
+CONFIG_ACPI_BUTTON=y
+CONFIG_ACPI_REDUCED_HARDWARE_ONLY=y
```

</details>

mostly `CONFIG_VIRTIO_FS` sounds important

**Comment by Mic92** [comment]
If the project would live in the nix-community space, than we could use the community binary cache (1TB)...

**Comment by GTrunSec** [comment]
currently, we just need to separate the kernelpackgae to be a package in packages that is enough to build a cache. 

https://github.com/astro/microvm.nix/blob/main/nixos-modules/microvm.nix#L18

```
microvm-kernel =  prev.linuxPackages_latest.extend (_self: super: {
    kernel = super.kernel.override {
```

**Comment by astro** [comment]
That's now merged with #11

**Comment by astro** [comment]
I have started building both the **main** branch and the daily-updated **update_flake_lock_action** on a Hydra instance:
- https://hydra.hq.c3d2.de/jobset/c3d2/microvm.nix#tabs-jobs
- https://hydra.hq.c3d2.de/jobset/c3d2/microvm.nix-update#tabs-jobs

```
substituters = https://nix-serve.hq.c3d2.de
trusted-public-keys = nix-serve.hq.c3d2.de:KZRGGnwOYzys6pxgM8jlur36RmkJQ/y8y62e52fj1ps=
```

**Comment by milahu** [comment]
thanks : )

lets add a `binary release` section to the readme?

a bit more verbose:

```nix
# /etc/nixos/configuration.nix
{
          nix.extraOptions = ''
            # nix flakes
            experimental-features = nix-command flakes
            keep-outputs = true
            keep-derivations = true
            # x86_64-linux.vm-firecracker etc
            # https://github.com/astro/microvm.nix/issues/3
            substituters = https://nix-serve.hq.c3d2.de
            trusted-public-keys = nix-serve.hq.c3d2.de:KZRGGnwOYzys6pxgM8jlur36>
          '';
```

```sh
sudo nixos-rebuild switch
nix registry add microvm github:astro/microvm.nix
# TODO pin microvm in /etc/nixos/flake.nix
nix run microvm#firecracker-example
# ... fetching linux-5.16.10-dev from https://nix-serve.hq.c3d2.de ...
```

**Comment by astro** [comment]
I have now setup Github actions with a Cachix cache. I've added the corresponding settings to the flake.nix so that you can easily obtain the Linux kernel built by Microsoft.

**Comment by milahu** [comment]
> I have now setup Github actions with a Cachix cache.

yepp [.github/workflows/kernel-package.yml](https://github.com/astro/microvm.nix/blob/main/.github/workflows/kernel-package.yml)

> I've added the corresponding settings to the flake.nix

where? or is this automagic?

> so that you can easily obtain the Linux kernel built by Microsoft.

^^

**Comment by astro** [comment]
Oops, forgot to commit. 59d7cef5c85d061afe9cdd8f7d59330d81fa4a6e
