### ISSUE TITLE
Deleting microvms does not delete all associated resources

### ISSUE THREAD

**Issue by pecigonzalo** [astro/microvm.nix#302]
Hi! Im declaring VMs with the declarative approach inside of my NixOS config. When microvms are deleted, there are some network resources that seem to be left behind and not removed.

- tuntap devices
- microvms themeselves in `/var/lib/microvms`

Shouldn't these be cleaned up when the microvm is undeclared?

Thanks

**Comment by romner-set** [comment]
Also running into this after upgrading to 24.11, it's causing my VMs to completely lose networking after `microvm -Ru` or similar commands.

For me it's happening in the `microvm-tap-interfaces@` stop script, specifically [this line](https://github.com/astro/microvm.nix/blob/e8d5f12b834a59187c7ec147a8952a0567f97939/nixos-modules/host/default.nix#L143) is erroring out with `ioctl(TUNSETIFF): Invalid argument`. Replacing the command with `ip link del $id` seems to fix it.

**Comment by astro** [comment]
Thanks!

It seems that `ip link delete` is much less picky than `ip tuntap del`, so let's use it!

**Comment by pecigonzalo** [comment]
Chiming back in here, I don’t think it’s just the links. The VMs are left
running for example. I would expect this to work like the container NixOS
module that removes them if removed from the declared code.

Does that make sense?

**Comment by astro** [comment]
The systemd units are explicitly not restarted on the host's `nixos-rebuild switch` because they are updated independently.

What do you think about adding a section to the FAQ in the handbook? Would that help?

**Comment by astro** [comment]
The VMs are updated independently when managing them imperatively via `microvm -u`.

I'd accept PRs that stop declarative VMs on removal but I'm very vary of automatically removing state for VMs that are perhaps only deactivated temporarily.

**Comment by pecigonzalo** [comment]
Yeah, in the imperative use case I can see it, but in the declarative they
are not behaving as expected right?

I’ll try and cook up a PR

**Comment by pecigonzalo** [comment]
@astro I think the change would be to set [restartIfChanged](https://search.nixos.org/options?channel=24.11&show=systemd.services.%3Cname%3E.restartIfChanged&from=50&size=50&sort=relevance&type=packages&query=services.%3Cname) to true (by removing it). 

This is what I believe makes the difference in the `container-oci`, but its explicitly set to `false` in `microvm.nix` [eg.](https://github.com/astro/microvm.nix/blob/main/nixos-modules/host/default.nix#L134).
I would suggest to `true`, like in `container-oci` and provide an option to set it to `false` for those that are running the VMs imperatively.

What do you think?

**Comment by astro** [comment]
@pecigonzalo I think imperative MicroVMs are the more common use-case because:
- Nix evaluation of multiple systems doesn't scale well
- You don't want to restart all VMs for a small host config change

**Comment by pecigonzalo** [comment]
I can do the opposite then, but I think imperative is the opposite of what Nix is meant to do 90% of the time. 

Do you have statistics on imperative being the most used? I'll take a guess and suspect you get more issues for it, but that does might not mean more use, just more problems.

Nevertheless it's quite simple for those that don't want to do imperative like me to flip the flag as well. So if the solution sounds good to you I'll send the PR with the var for those that use declarative toggle it and be able to get VMs to behave the same as oci-container.

**Comment by astro** [comment]
> I can do the opposite then, but I think imperative is the opposite of what Nix is meant to do 90% of the time.

Thank you for your understanding. I generally agree, it's just not practical.

> Do you have statistics on imperative being the most used? I'll take a guess and suspect you get more issues for it, but that does might not mean more use, just more problems.

I will not snoop on users. Ideas:
- Running a long-term survey
- Opt-in telemetry

> Nevertheless it's quite simple for those that don't want to do imperative like me to flip the flag as well. So if the solution sounds good to you I'll send the PR with the var for those that use declarative toggle it and be able to get VMs to behave the same as oci-container.

👍
