### ISSUE TITLE
How do I use `configuration.nix` in a microvm?

### ISSUE THREAD

**Issue by sekunho** [astro/microvm.nix#33]
Hello! First off, thanks for creating something really cool.

I'm trying to build a basic VM with this but I'm not sure how I'm supposed to use a `configuration.nix` file for this. Am I supposed to treat this as a normal NixOS machine, except as a VM? Am I able to configure the kernel version, or NixOS state version for example like normal? One of the reasons is I don't want to build the latest kernel from scratch, and I rather just reuse the kernel package the host system has.

Here's what I tried:

```nix
modules = [
  # Include the microvm module
  microvm.nixosModules.microvm
  # Add more modules here
  ({ pkgs, lib, ... }: {
    boot.kernelPackages = pkgs.linuxPackages_5_15;

    nix = {
      package = pkgs.nix_2_7;

      gc = {
        automatic = true;
        options = "--delete-older-than 14d";
      };

      extraOptions = ''
        experimental-features = nix-command flakes
        keep-outputs = true
        keep-derivations = true
      '';

      binaryCaches = [
        "https://hydra.iohk.io"
        "https://iohk.cachix.org"
        "https://nix-community.cachix.org"
      ];

      binaryCachePublicKeys = [
        "hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ="
        "iohk.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo="
        "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
      ];
    };

    networking.hostName = "microvm";
    microvm = {
      hypervisor = "cloud-hypervisor";
      mem = 256;
      vcpu = 1;
    };

    environment.systemPackages = [ pkgs.hello ];
  })
];
```

But this still seems to pull in 5.17 instead of 5.15 so I'm not sure if I'm using it the right way.

**Comment by astro** [comment]
What is your use-case for not building off a Flake? If it's important, maybe there is a way to make it compatible with non-Flakes Nix.

You need to build the kernel for reasons recently added to the [FAQ](https://astro.github.io/microvm.nix/faq.html#why-build-a-kernel-with-a-custom-config).
