### ISSUE TITLE
/init: line 9: /proc/cmdline: No such file or directory - firecracker-example

### ISSUE THREAD

**Issue by milahu** [astro/microvm.nix#4]
two potential problems in `microvm#firecracker-example`

```
/nix/store/da5ggpl6xx9i9c61n7jg8k11fyc9bb77-nixos-system-firecracker-microvm-21.05.20210901.110a2c9
/init: line 9: /proc/cmdline: No such file or directory

/nix/store/da5ggpl6xx9i9c61n7jg8k11fyc9bb77-nixos-system-firecracker-microvm-21.05.20210901.110a2c9
/init: line 117: /dev/fd/62: No such file or directory
```

line 9

```sh
# Process the kernel command line.
for o in $(</proc/cmdline); do
```

&rarr; maybe proc is not mounted?

line 117

```sh
# Log the script output to /dev/kmsg or /run/log/stage-2-init.log.
# Only at this point are all the necessary prerequisites ready for these commands.
exec {logOutFd}>&1 {logErrFd}>&2
if test -w /dev/kmsg; then
    exec > >(tee -i /proc/self/fd/"$logOutFd" | while read -r line; do
```

full output

<details>

<pre>
<span color="turquoise">[nix-shell:~/src/firecracker]$</span> nix registry add microvm github:astro/microvm.nix

<span color="turquoise">[nix-shell:~/src/firecracker]$</span> nix flake init -t microvm

<span color="turquoise">[nix-shell:~/src/firecracker]$</span> nix run microvm#firecracker-example
[<span color="blue">1</span>/<span color="turquoise">181</span>/195 built, <span color="turquoise">305</span> copied (<span color="turquoise">1364.5</span> MiB), <span color="turquoise">394.1</span> MiB DL] building <span color="#ffffff">linux-5.13.13</span> (buildPhase):   CC      drivers/iommu/amd/init.o
1+0 records in
1+0 records out
1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.00368099 s, 285 MB/s
mke2fs 1.46.2 (28-Feb-2021)
Discarding device blocks: done
Creating filesystem with 262144 1k blocks and 65536 inodes
Filesystem UUID: 537e9a22-10e7-4372-81cb-fefd514fdf5f
Superblock backups stored on blocks:
        8193, 24577, 40961, 57345, 73729, 204801, 221185

Allocating group tables: done
Writing inode tables: done
Creating journal (8192 blocks): done
Writing superblocks and filesystem accounting information: done

<span color="turquoise">INFO</span>[0000] Called startVMM(), setting up a VMM on microvm-firecracker-microvm.firecracker
<span color="turquoise">INFO</span>[0000] VMM logging and metrics disabled.
<span color="turquoise">INFO</span>[0000] refreshMachineConfig: [GET /machine-config][200] getMachineConfigOK  &amp;{CPUTemplate:Uninitialized HtEnabled:true MemSizeMib:512 VcpuCount:1}
<span color="turquoise">INFO</span>[0000] PutGuestBootSource: [PUT /boot-source][204] putGuestBootSourceNoContent
<span color="turquoise">INFO</span>[0000] Attaching drive var.img, slot 2, root false.
<span color="turquoise">INFO</span>[0000] Attached drive var.img: [PUT /drives/{drive_id}][204] putGuestDriveByIdNoContent
<span color="turquoise">INFO</span>[0000] Attaching drive /nix/store/cf88rbcpcq55sjp74agdn8b2jzf5b8pw-rootfs-firecracker-microvm.squashfs, slot 1, root true.
<span color="turquoise">INFO</span>[0000] Attached drive /nix/store/cf88rbcpcq55sjp74agdn8b2jzf5b8pw-rootfs-firecracker-microvm.squashfs: [PUT /drives/{drive_id}][204] putGuestDriveByIdNoContent
<span color="turquoise">INFO</span>[0000] startInstance successful: [PUT /actions][204] createSyncActionNoContent
[    0.004893] ACPI BIOS Error (bug): A valid RSDP was not found (20210331/tbxfroot-210)
[    0.145325] PCI: Fatal: No config space access function found
�2021-10-08T03:43:40.623482924 [anonymous-instance:fc_vcpu 0:WARN:src/devices/src/legacy/i8042.rs:126] Failed to trigger i8042 kbd interrupt (disabled by guest OS)
2021-10-08T03:43:40.633010965 [anonymous-instance:fc_vcpu 0:WARN:src/devices/src/legacy/i8042.rs:126] Failed to trigger i8042 kbd interrupt (disabled by guest OS)
/nix/store/da5ggpl6xx9i9c61n7jg8k11fyc9bb77-nixos-system-firecracker-microvm-21.05.20210901.110a2c9/init: line 9: /proc/cmdline: No such file or directory

<span color="turquoise">&lt;&lt;&lt; NixOS Stage 2 &gt;&gt;&gt;</span>

mount: /: cannot remount none read-write, is write-protected.
mount: /dev: devtmpfs already mounted or mount point busy.
/nix/store/da5ggpl6xx9i9c61n7jg8k11fyc9bb77-nixos-system-firecracker-microvm-21.05.20210901.110a2c9/init: line 117: /dev/fd/62: No such file or directory
running activation script...
setting up /etc...
starting systemd...

<span color="turquoise">&lt;&lt;&lt; Welcome to NixOS 21.05.20210901.110a2c9 (x86_64) - ttyS0 &gt;&gt;&gt;</span>

firecracker-microvm login: 
</pre>

</details>

**Comment by astro** [comment]
Fixed in adb3d745f5a6b936145c8fca9fd26d72efd72799
