### ISSUE TITLE
tap requires root

### ISSUE THREAD

**Issue by milahu** [astro/microvm.nix#5]
as nonroot i get

> ```$ nix run .#firecracker-example-with-tap```
> ...
> ```INFO[0000] Attaching NIC fire-eth0 (hwaddr 00:02:00:01:02:02) at index 1 ```
> ```2021-10-08T16:03:34.128068904 [anonymous-instance:fc_api:ERROR:src/api_server/src/parsed_request.rs:122] Received Error. Status code: 400 Bad Request. Message: Could not create Network Device: TapOpen(IoctlError(Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }))```
> ```WARN[0000] Failed handler "fcinit.CreateNetworkInterfaces": [PUT /network-interfaces/{iface_id}][400] putGuestNetworkInterfaceByIdBadRequest  &{FaultMessage:Could not create Network Device: TapOpen(IoctlError(Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }))} ```
> ```FATA[0000] Failed to start machine: [PUT /network-interfaces/{iface_id}][400] putGuestNetworkInterfaceByIdBadRequest  &{FaultMessage:Could not create Network Device: TapOpen(IoctlError(Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }))}```

can we throw earlier?
~~can we use tap as nonroot?~~
can we start network as nonroot?

**Comment by astro** [comment]
Not that I know of.

When running MicroVMs declaratively, interface creation is done as root in a systemd service: https://github.com/astro/microvm.nix/blob/main/nixos-modules/host.nix
