### ISSUE TITLE
VM squashfs gets built twice with declarative build

### ISSUE THREAD

**Issue by Sohalt** [astro/microvm.nix#53]
The VM squashfs always gets built twice. First when building the host, which has something like `microvm.vms.foo.flake = self;` and then a second time when updating the vm on the host using `$ microvm -Ru foo`.
Is there a way around that?
Ideally I'd only build the squashfs as part of the host and automatically restart the VM inside the activationScript for the host, if it has changed.

**Comment by astro** [comment]
The host-declarative MicroVM is practical to ensure existence of a critical MicroVM (eg. for network access). Too many of these will stretch evaluation time of the host to unbearable length and multiply memory usage. Are you sure you want to continue with that? If so, maybe don't use `microvm -u` on these?

To satisfy your wish we would have to determine which MicroVM is actually newer: the declaratively installed system, or the imperatively managed one with `microvm -u`? Any ideas?

**Comment by astro** [comment]
> Ideally I'd only build the squashfs as part of the host and automatically restart the VM inside the activationScript for the host, if it has changed.

Closing in favor of #94 where solutions to this are discussed.
