### ISSUE TITLE
QEMU MicroVMs do not respect `microvm.vcpu` option

### ISSUE THREAD

**Issue by kraftnix** [astro/microvm.nix#60]
I noticed recently that all QEMU MicroVMs I spawned were always limited to 1 CPU, no matter how many I specified in `microvm.vcpu`. I have tested the same MicroVM config with a `cloud-hypervisor` hypervisor, and the `cloud-hypervisor` VM correctly assigns the correct number of vCPUs.

## Reproduction Steps

1. clone repo
2. modify `makeExample` to include `microvm.vcpu = 4;`
3. launch test VM with `nix run .#qemu-example`
4. login and check number of CPUs available with `cat /proc/cpuinfo` or `lscpu`

> doing the same with `nix run #cloud-hypervisor-example` will show the correctly specified number of vCPUs.

**Comment by astro** [comment]
Confirmed. Thank you for reporting!

Despite passing `-smp` to qemu...
