### ISSUE TITLE
Cleaning up microvms

### ISSUE THREAD

**Issue by nmaki** [astro/microvm.nix#67]
Not entirely clear how to best cleanup microvm's.

Specifically I have some microvms that were added to a flake declaratively that run on qemu. I've tried removing them from my flake which didnt seem to do any cleanup or stop any running vm's.

Any direction or documentation on this would be greatly appreciated.

**Comment by astro** [comment]
```bash
systemctl stop microvm@$NAME
rm -rf /var/lib/microvms/$NAME
```

This should be part of the handbook, right?

**Comment by astro** [comment]
0a3d48e
