### ISSUE TITLE
Kernels possibly taken from wrong Nix store path

### ISSUE THREAD

**Issue by mikatammi** [astro/microvm.nix#69]
I'm trying to make MicroVM.nix work on aarch64-linux host architecture with aarch64-linux guests

For me it looks like kernel is taken from wrong path: I see `"${kernel.dev}/vmlinux"` all over the place, I think this should be `"${kernel.out}/Image"` instead

That seems to not cause errors on x86_64 host, but on aarch64 I can see clear errors about kernel image being wrong type with crosvm, and QEMU just doesn't do anything

**Comment by astro** [comment]
Sorry for the sad state of aarch64 support here. I got tired of waiting for my RPi4.

I am going to be very happy about PRs.

**Comment by mikatammi** [comment]
There probably will be few :)

**Comment by mikatammi** [comment]
What concerns me about this vmlinux vs. Image -thing, is that is there some benefit for using the vmlinux-image on x86_64? My educated guess is that the vmlinux has the debugging information, but if one does not do kernel debugging, is there any benefit for using vmlinux instead of Image.

For the PR I'm just thinking should I make this conditional based on system architecture, or just change to Image altogether?

**Comment by astro** [comment]
One of the hypervisors wanted the Image, it couldn't load vmlinux.

On a side note I am currently trying to build https://github.com/cloud-hypervisor/rust-hypervisor-firmware in the hope that we can boot ELF kernel + initramfs on all of the five hypervisors.

**Comment by mikatammi** [comment]
You are right, we need ELF for x86_64 and the (b)zImage for aarch64. I guess there are really no other architectures with virtualization right now, maybe PPC and also RISC-V in the future
