### ISSUE TITLE
Prebuilding kernel for aarch64

### ISSUE THREAD

**Issue by rbozan** [astro/microvm.nix#73]
Hi, I was wondering whether it is a good idea to have Github Actions prebuild the kernel for aarch64 ? It seems Github Actions might not support building for it natively but you can do it through qemu, although it will be slow.

**Comment by astro** [comment]
With qemu-user we will run into time limits on Github. I am open for alternative solutions.

On the other hand, I am currently trying to do away with a custom kernel by using NixOS' initrd.

**Comment by astro** [comment]
@rbozan @ahirner The initrd branch is slowly getting in shape. Give it a try if you suffer a lot from having to build the microvm-kernel on the main branch. (I myself haven't tested on aarch64, see #72.)
