### ISSUE TITLE
Is is possible to define a custom microvm-kernel configuration?

### ISSUE THREAD

**Issue by jkuro-tii** [astro/microvm.nix#74]
I want to use the microvm package from another flake.nix file. I'd like to be able to run virtual machines with custom kernels configurations and patches set. Is it possible to override the config defined in the pkgs/microvm-kernel.nix file from another flake.nix file?

**Comment by astro** [comment]
Try something like this in your NixOS config:
```nix
nixpkgs.config.packageOverrides = pkgs: {
 microvm-kernel = pkgs.microvm-kernel.override {
   extraConfig = ''
     ...
   '';
 };
};
```

Does that work for you?

**Comment by jkuro-tii** [comment]
Hi,
Thank you for fast response!
I'm building the solution using microvm on Fedora Linux, not NixOS, thus I can't apply your fix to its config.
In the solution  (https://github.com/tiiuae/ghaf/blob/main/microvmConfigurations/netvm/default.nix) microvm is used as a NixOS module; I'm investigating now how modules work.

Best Regards,

Jarek.
[https://opengraph.githubassets.com/b51ef4a08bab0b05cf5c96436044c87d5c054747f778b4e6438baa2ab9c69a56/tiiuae/ghaf]<https://github.com/tiiuae/ghaf/blob/main/microvmConfigurations/netvm/default.nix>
ghaf/default.nix at main · tiiuae/ghaf<https://github.com/tiiuae/ghaf/blob/main/microvmConfigurations/netvm/default.nix>
Documentation for TII SSRC Common Tech - https://tiiuae.github.io/ghaf/ - ghaf/default.nix at main · tiiuae/ghaf
github.com

[https://opengraph.githubassets.com/d2037370ff499ed7afbb45be1145ad10d52893fce89525315136e60683f30bd4/jkuro-tii/ghaf]<https://github.com/jkuro-tii/ghaf/blob/main/microvmConfigurations/netvm/default.nix>
ghaf/default.nix at main · jkuro-tii/ghaf<https://github.com/jkuro-tii/ghaf/blob/main/microvmConfigurations/netvm/default.nix>
Documentation for TII SSRC Common Tech - https://tiiuae.github.io/ghaf/ - ghaf/default.nix at main · jkuro-tii/ghaf
github.com


________________________________

**Comment by astro** [comment]
In contrast to containers, virtual machines have their own kernel. Put the kernel overrides in the microvm's nixos config.
