### ISSUE TITLE
extra `lib` causes evaluation of most `runners` to fail

### ISSUE THREAD

**Issue by ahirner** [astro/microvm.nix#76]
As evidenced [in CI](https://github.com/astro/microvm.nix/runs/11839524075). Introduced in https://github.com/astro/microvm.nix/commit/23faa2673232bef086b68d0ea471f71d1262372e
I wonder what #23faa26 intended, since `lib` remains inherited from `pkgs` in `cloud-hypervisor.nix`.

If the extra `lib` was unintended, [the fix](https://github.com/astro/microvm.nix/compare/main...ahirner:microvm.nix:bugfix/extra_lib?expand=1) is to simply remove `lib`.

**Comment by astro** [comment]
Thank you for preparing the fix.
