### ISSUE TITLE
unable to configure NAT for host-only networking with bridge

### ISSUE THREAD

**Issue by omernaveedxyz** [astro/microvm.nix#77]
I am trying to setup my microVM configuration so that the VM's are able to communicate with the host as well as other VM's, and also communicate with the outside internet; however, I do not want the VM's showing up as separate network devices. Following this [guide](https://wiki.archlinux.org/title/QEMU#Host-only_networking), I figured that host-only networking with NAT would fullfill my needs.

I have managed to get the VM's to communicate with each other and the host, but I am having trouble with setting up NAT. Any help would be greatly appreciated.

Host configuration
```
networking.firewall.allowedTCPPorts = [ 80 ];

microvm.vms = {
  "my-microvm" = {
    flake = inputs.self;
    updateFlake = "...";
  };
};
networking.bridges = {
  "virbr0" = {
    interfaces = [ ];
  };
};
networking.interfaces = {
  "virbr0".ipv4.addresses = [
    { address = "192.168.10.1"; prefixLength = 24; }
  ];
};
# TODO: not working
networking.nat = {
  enable = true;
  externalInterface = "wlp59s0";
  internalInterfaces = [ "virbr0" ];
};
```

MicroVM configuration
```
my-microvm = inputs.nixpkgs.lib.nixosSystem {
  system = "x86_64-linux";
  modules = [
    inputs.microvm.nixosModules.microvm
    {
      networking.firewall.allowedTCPPorts = [ 80 443 ];
      microvm = {
        ...
        interfaces = [
          {
            type = "bridge";
            id = "eth0";
            mac = "02:00:00:00:00:01";
            bridge = "virbr0";
          }
        ];
      };
      networking.useNetworkd = true;
      systemd.network = {
        enable = true;
        netdevs."virbr0".netdevConfig = {
          Kind = "bridge";
          Name = "virbr0";
        };
        networks."00-eth" = {
          matchConfig.MACAddress = "02:00:00:00:00:01";
          networkConfig.Bridge = "virbr0";
        };
        networks."01-virbr0" = {
          matchConfig.Name = "virbr0";
          networkConfig = {
            DHCP = "ipv4";
            IPv6AcceptRA = true;
          };
          addresses = [{ addressConfig.Address = "192.168.10.2/24"; }];
        };
      };
    }
  ];
};
```

**Comment by astro** [comment]
Your MicroVM has both DHCP/IPv6AcceptRA and a static address. I think only the static address is valid because your host doesn't run dhcpd or radvd on virbr0.

Your NAT setup on the host looks alright. The MicroVM is missing a default route for Internet addresses. Add below `addresses`:

```nix
gateway = [ "192.168.10.1" ];
```

Please close the issue if this solves your problem.

**Comment by omernaveedxyz** [comment]
That was it! It seems obvious in hindsight, but I was hitting my head against the wall for a while trying to solve this. Thank you!
