### ISSUE TITLE
issues building checks for `cloud-hypervisor`, `kvmtool` and `crosvm`

### ISSUE THREAD

**Issue by kraftnix** [astro/microvm.nix#78]
On the current `main` branch, I cannot build the following checks, but they succeed with `qemu` and `firecracker` hypervisors:
- `checks.x86_64-linux.vm-cloud-hypervisor`
- `checks.x86_64-linux.vm-kvmtool`
- `checks.x86_64-linux.vm-crosvm`

The variants of the above tests such as `*-iperf` also fail.

They all fail due to not having access to `/dev/kvm` within the test QEMU VM.
```
microvm@x86_64-linux-cloud-hypervisor-example[916]: Writing superblocks and filesystem accounting information: done
microvm@x86_64-linux-cloud-hypervisor-example[907]: Failed to open hypervisor interface (is hypervisor interface available?): Failed to create the hypervisor: no supported hypervisor
```

I have a few checks in a private project which uses microvm with `cloud-hypervisor` in tests and don't have this issue (as long as the tests run on a host which allows nested virtualisation with `options kvm_{amd|intel} nested=1`). I am not sure about why there are no issues in my downstream project vs here.

**Comment by astro** [comment]
This project needs better CI. All I have so far is [a Hydra jobset](https://hydra.hq.c3d2.de/jobset/c3d2/microvm.nix#tabs-jobs).

**Comment by kraftnix** [comment]
The `vm-*` and and `*-iperf` tests pass on my machine if I change the test VM's QEMU cpu options for `x86_64-linux` to `host`.

There is a branch [here](https://github.com/kraftnix/microvm.nix/commits/fix/kvm-nested-checks) with the changes, I am not sure how these options will work with the CI but do you want me to make a PR?

**Comment by astro** [comment]
The change reads as if we're losing the `vmx` feature... or, maybe I did get the syntax wrong in the first place?

I really don't think `host` are going to be enough in all cases. `vmx` should be emulated by qemu even if nested KVM is not available.

It appears that merely adding the CPU flag has ceased to make Linux' kvm_intel work. Yet that does not appear to be case with the rival technology SVM, which I switched to in 213475e01136d316ed58d5fe38a361cc6b13a661. Works for you?

**Comment by kraftnix** [comment]
You are right, I wasn't considering the differences in AMD vs Intel.

The change in your branch makes the tests pass on an AMD host, but breaks when run on an Intel host.

It turns out you can just enable both (`kvm64,vmx=on,+svm`), and it works for both AMD and Intel hardware, see https://github.com/kraftnix/microvm.nix/commit/ee71fd9ddeed45b662dd7d998be31282d6f326ff.

**Comment by astro** [comment]
I enabled it with consistent syntax ;)

Does that make the checks build for you?
