### ISSUE TITLE
Support MACVTAP as an alternative to classical TUN/TAP

### ISSUE THREAD

**Issue by oddlama** [astro/microvm.nix#80]
I've been using MACVTAP networking instead of classical TUN/TAP networking on my VMs for some time and would like to do the same when finally migrating to microvm.nix. MACVTAPs have some advantages over TUN/TAP interfaces that I learned to appreciate, but also some downsides so this probably isn't a replacement for TUN/TAP networking.

Put shortly, it is a much simpler driver that eliminates a whole layer by giving each guest it's own physical address. This _vastly_ reduces the processing needed on the host and allows for high-throughput between host and guests without putting additional stress on the CPU. It can also be used to fully isolate host and guest traffic (by operating in private or passthrough mode and not creating a vtap for the host), if so desired. While IBM does report [improvements in performance between 10-50%](https://www.ibm.com/docs/en/linux-on-systems?topic=cons-macvtap-driver-considerations), I can personally only attest to the reduction in required compute. Thus I believe it would make for a great feature for microvm.nix.

Also, see [the diagrams in this redhat guide](https://developers.redhat.com/blog/2018/10/22/introduction-to-linux-interfaces-for-virtual-networking#macvtap) for a visual comparison between MACVTAP and TAP/TUN architectures. As a quick reference, here's what a typical setup using systemd-networkd would entail:

Create a macvtap device in bridge mode (to allow guest-guest networking):
```desktop
# /etc/systemd/network/br-eth0.netdev
[NetDev]
Name=br-eth0
Kind=macvtap

[MACVTAP]
Mode=bridge
```

The host's networking is configured on the macvtap interface to allow host-guest networking:
```desktop
# /etc/systemd/network/br-eth0.network
[Match]
Name=br-eth0

[Network]
# host network configuration, whatever it would otherwise want for eth0 directly
Address=192.168.1.1/24

# This is necessary to prevent an unconfigured bridge when the attached physical
# device fails to come up. If for example the LAN cable is removed from the real
# interface, we still want a static ip on the bridge to allow our virtual machines
# to function correctly.
ConfigureWithoutCarrier=yes
```

Attach the macvtap to eth0
```desktop
# /etc/systemd/network/eth0.network
[Match]
Name=eth0

[Network]
MACVTAP=br-eth0
```

Each guest can now get it's own macvtap interface. Probably depends on the hypervisor on how to set that up - I previously used libvirt which does that on demand.

---

Additional relevant resources:

[1] https://www.ibm.com/docs/en/linux-on-systems?topic=cons-macvtap-driver-considerations
[2] https://access.redhat.com/documentation/de-de/red_hat_enterprise_linux/6/html/virtualization_administration_guide/sect-attch-nic-physdev
[3] https://suhu0426.github.io/Web/Presentation/20150120/index.html

And specifically about enabling host-guest networking:

[4] http://www.furorteutonicus.eu/2013-08-04-enabling-host-guest-networking-with-kvm-macvlan-and-macvtap
[5] https://www.math.cmu.edu/~gautam/sj/blog/20140303-kvm-macvtap.htm

**Comment by megheaiulian** [comment]
With qemu we can attach a macvtap by using:
```
-net nic,model=virtio,macaddr=$MACADDR \
-net tap,fd=3 3<>/dev/tap$(ip link show $MACVLN | head -1 | cut -d: -f1)
```
Where MACADDR is the mac address and MACVLN is a macvtap interface.
With microvm it looks like a `fd` option could be added at https://github.com/astro/microvm.nix/blob/main/lib/runners/qemu.nix#L142 but maybe its better to have a `macvtap` type of network to support other hypervisors.

**Comment by astro** [comment]
For consistency I'd like to create the interface like it is already done with tuntap interfaces.

Is there a more graceful way than opening the device node in shell and passing the fd?

**Comment by megheaiulian** [comment]
Unfortunately it seems like there is no better way to handle this.
Documentation about `macvtap` is quite scarce but I'll link some of the most interesting resource I found about it:  
 - https://backreference.org/2014/03/20/some-notes-on-macvlanmacvtap/index.html
 - https://lists.gnu.org/archive/html/qemu-devel/2016-12/msg00947.html
 - https://github.com/finallyjustice/sample/blob/master/kvm/macvtap.txt
 
I think there needs to be a new `macvtap` type of interface supporting `mac` &`id option. 
A service or netdev to create the interface itself and maybe chmod/chown its tap to the user & permissions needed might also make sense.

**Comment by megheaiulian** [comment]
@astro Thank you for implementing this! I've tested it and it works properly.

I've used this configuration to create the macvtap interface:
```nix
{
  systemd.network.netdevs.jrsptap = {
    netdevConfig = {
      Name = "jrsptap";
      Kind = "macvtap";
      MACAddress = "...";
    };
  };
  systemd.network.networks.vms = {
    matchConfig.Name = "vms";
    extraConfig = ''
      [Network]
      MACVTAP=jrsptap
    '';
  };
  systemd.services.jrstap-own =
    {
      description = "Setup macvtap";
      wantedBy = [ "sys-devices-virtual-net-jrsptap.device" ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStart = pkgs.writeShellScript "jrsptap-own" ''
          ${pkgs.coreutils-full}/bin/chown microvm:kvm /dev/tap$(${pkgs.coreutils-full}/bin/cat /sys/class/net/jrsptap/ifindex)
          ${pkgs.coreutils-full}/bin/chmod g+rw /dev/tap$(${pkgs.coreutils-full}/bin/cat /sys/class/net/jrsptap/ifindex)
        '';
      };
    };
  systemd.network.wait-online.ignoredInterfaces = [ "jrstap" ];
}
```
and this for the vm:

```
    microvm.interfaces = [{
      type = "macvtap";
      id = "jrsptap";
      mac = "...";
    }];

```

Because this is a little verbose to setup per vm I think it might make sense to create  a `microvm-macvtap-interfaces@` service that does this setup? In that case the `id` would point to the target interface (a vlan named `vms` in my config) instead of the macvtap itself.

**Comment by megheaiulian** [comment]
But now I see that the `microvm-macvtap-interfaces@` does it a bit better because the interfaces are created and removed on demand.
