### ISSUE TITLE
Wayland VMs / wayland-proxy-virtwl virtio-gpu proxy support

### ISSUE THREAD

**Issue by 0xc1c4da** [astro/microvm.nix#83]
microvm.nix could offer a clean way to offer reasonably secure desktop computing experience to existing Nix installations. Through the support Wayland GUI VM compartmentalization on personal computers, similar to [Qubes OS](https://www.qubes-os.org/).

Approaches have leveraged Nix to implement similar features, ie [Spectrum OS](https://spectrum-os.org/) and [qubes-lite](https://gitlab.com/talex5/qubes-lite) using Wayland. The main issues with these approaches is that Spectrum requires installing Spectrum from scratch, is under development and is difficult to retrofit onto an existing Nix installation, and qubes-lite is a personal script hacked together.

Rather than #57 where the gpu is passed through to a vm, the gpu can be shared across vms, and the vm's Wayland clients can be proxied to the host's compositor, using [wayland-proxy-virtwl ](https://github.com/talex5/wayland-proxy-virtwl) `--virtio-gpu`.

crosvm supports virtio-gpu natively, and Spectrum [has patches that enables it for cloud-hypervisor](https://spectrum-os.org/git/nixpkgs/tree/pkgs/applications/virtualization/cloud-hypervisor/default.nix?h=wayland). Wayland-proxy-virtwl is already included in [nixpkgs pkgs/tools/wayland/wayland-proxy-virtwl/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/wayland/wayland-proxy-virtwl/default.nix).

Some examples of its usage:
- https://gitlab.com/talex5/qubes-lite/-/blob/master/default.nix#L183
- https://spectrum-os.org/git/spectrum/tree/release/checks/wayland/default.nix?h=wayland&id=aefa4eb3d4618a1e6d8e4d2677fb1a97d3b80f58#n18

**Comment by astro** [comment]
I have pushed some basic infrastructure work to the `graphics` branch. If you say this is useful already, I can merge it.

In general the virtio-gpu Wayland situation seems a bit outdated and thus flaky. The patches that improved things do no longer apply to the latest crosvm/cloud-hypervisor versions. Let us keep track of the situation...

**Comment by alyssais** [comment]
> The patches that improved things do no longer apply to the latest crosvm/cloud-hypervisor versions.

crosvm shouldn't need any patches, but there is a serious unresolved [bug](https://issuetracker.google.com/issues/273574299) with crosvm as the VMM.

I've just updated the Spectrum Cloud Hypervisor patches to be compatible with CH 30 and 31, but there are some important caveats to using those patches:

- I can't commit to supporting any particular CH/crosvm versions at any particular time.
- They're not done yet (although I'm in the final stretch now — probably a matter of weeks before my todo list is cleared).  In particular, I think they still don't work at all on ARM.

**Comment by astro** [comment]
I have added an example: `nix run github:astro/microvm.nix/graphics#graphics`

In the long run, more useful would a wrapper like `nix run ...#run-graphics nixpkgs#package`

**Comment by astro** [comment]
The bit of JSON we pass to `crosvm device gpu` contains the same fields that can be passed to crosvm when running the GPU stuff in-process. I found them to be kinda ineffective, however. :-( Happy tinkering!

```
  --gpu             (EXPERIMENTAL) Comma separated key=value pairs for setting
                    up a virtio-gpu device
                    Possible key values:
                        backend=(2d|virglrenderer|gfxstream) - Which backend to
                           use for virtio-gpu (determining rendering protocol)
                        displays=[[GpuDisplayParameters]] - The list of virtual
                            displays to create. See the possible key values for
                            GpuDisplayParameters in the section below.
                        context-types=LIST - The list of supported context
                          types, separated by ':' (default: no contexts enabled)
                        width=INT - The width of the virtual display connected
                           to the virtio-gpu.
                           Deprecated - use `displays` instead.
                        height=INT - The height of the virtual display
                           connected to the virtio-gpu.
                           Deprecated - use `displays` instead.
                        egl[=true|=false] - If the backend should use a EGL
                           context for rendering.
                        glx[=true|=false] - If the backend should use a GLX
                           context for rendering.
                        surfaceless[=true|=false] - If the backend should use a
                            surfaceless context for rendering.
                        angle[=true|=false] - If the gfxstream backend should
                           use ANGLE (OpenGL on Vulkan) as its native OpenGL
                           driver.
                        vulkan[=true|=false] - If the backend should support
                           vulkan
                        wsi=vk - If the gfxstream backend should use the Vulkan
                           swapchain to draw on a window
                        cache-path=PATH - The path to the virtio-gpu device
                           shader cache.
                        cache-size=SIZE - The maximum size of the shader cache.
                        pci-bar-size=SIZE - The size for the PCI BAR in bytes
                           (default 8gb).
                    Possible key values for GpuDisplayParameters:
                        mode=(borderless_full_screen|windowed[width,height]) -
                           Whether to show the window on the host in full
                           screen or windowed mode. If not specified, windowed
                           mode is used by default. "windowed" can also be
                           specified explicitly to use a window size different
                           from the default one.
                        hidden[=true|=false] - If the display window is
                           initially hidden (default: false).
                        refresh-rate=INT - Force a specific vsync generation
                           rate in hertz on the guest (default: 60)
                        dpi=[INT,INT] - The horizontal and vertical DPI of the
                           display (default: [320,320])
                        horizontal-dpi=INT - The horizontal DPI of the display
                           (default: 320)
                           Deprecated - use `dpi` instead.
                        vertical-dpi=INT - The vertical DPI of the display
                           (default: 320)
                           Deprecated - use `dpi` instead.
```

**Comment by astro** [comment]
While far from being perfect and sustainable, this feature is that much nice to have that I polished it a bit and merged it into main.
